server:
  port: 8000

spring:
  application:
    name: cloud-consumer-order
  cloud:
    consul:
      host: 192.168.71.128
      port: 8500
      discovery:
        service-name: ${spring.application.name}

service:
  payment: http://cloud-provider-payment
