server:
  port: 8002

spring:
  application:
    name: cloud-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.71.128:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: FN5HW5Y1XQJ742I7

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.example.entities

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "http://192.168.0.103:7001/eureka/"
  instance:
    instance-id: payment_8002
    prefer-ip-address: true