server:
  port: 7001

eureka:
  instance:
    hostname: 192.168.0.103
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: "http://${eureka.instance.hostname}:${server.port}/eureka/"