server:
  port: 8000

spring:
  application:
    name: cloud-consumer-order

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "http://192.168.0.103:7001/eureka/"

service:
  payment: http://cloud-provider-payment

ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000

logging:
  level:
    org.example.service.PaymentService: debug
